# Generated by Django 4.2.3 on 2023-07-03 12:03

from django.db import migrations, models
import library1.models


class Migration(migrations.Migration):

    dependencies = [
        ('library1', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=100)),
                ('isbn', models.CharField(max_length=13)),
                ('issued_date', models.DateField(auto_now=True)),
                ('expiry_date', models.DateField(default=library1.models.expiry)),
            ],
        ),
    ]
